name: spring ci

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Execute check without tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check -x test

  test:
    runs-on: ubuntu-latest
    name: Testing on JDK 17
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Execute tests
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: test
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/@v2
        with:
          files: "build/test-results/**/*.xml"
